#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load base env (subscription, RG name, location)
source "$SCRIPT_DIR/../azure.env"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

require_var() {
	local name="$1"
	if [[ -z "${!name:-}" ]]; then
		echo "ERROR: Required env var '$name' is not set" >&2
		exit 1
	fi
}

# Path for generated, shared env values
GENERATED_ENV="$SCRIPT_DIR/.generated.env"

ensure_generated_env() {
	if [[ -f "$GENERATED_ENV" ]]; then
		return 0
	fi

	cat > "$GENERATED_ENV" <<'EOF'
# ------------------------------------------------------------------------------
# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Generated by infra scripts. Safe to delete; it will be recreated.
# ------------------------------------------------------------------------------
EOF
}

load_generated_env() {
	[[ -f "$GENERATED_ENV" ]] && source "$GENERATED_ENV"
}

# ------------------------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------------------------

require_var AZURE_SUBSCRIPTION_ID
require_var AZURE_RESOURCE_GROUP
require_var AZURE_LOCATION

# ------------------------------------------------------------------------------
# Azure context
# ------------------------------------------------------------------------------

echo "Using subscription: $AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"

# ------------------------------------------------------------------------------
# Resource Group
# ------------------------------------------------------------------------------

if az group show --name "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
	echo "Resource group '$AZURE_RESOURCE_GROUP' already exists."
else
	echo "WARNING: A new Azure resource group will be created."
	echo "  Name     : $AZURE_RESOURCE_GROUP"
	echo "  Location : $AZURE_LOCATION"
	echo
	echo "Press Ctrl+C within the next 10 seconds to cancel."
	sleep 10

	echo "Creating resource group '$AZURE_RESOURCE_GROUP' in '$AZURE_LOCATION'..."
	az group create \
		--name "$AZURE_RESOURCE_GROUP" \
		--location "$AZURE_LOCATION" \
		--output none
	echo "Resource group created."
fi

# ------------------------------------------------------------------------------
# Initialize generated env (if needed)
# ------------------------------------------------------------------------------

ensure_generated_env
load_generated_env

echo "Resource group setup complete."
