#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load base env
source "$SCRIPT_DIR/../azure.env"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

require_var() {
	local name="$1"
	if [[ -z "${!name:-}" ]]; then
		echo "ERROR: Required env var '$name' is not set" >&2
		exit 1
	fi
}

require_cmd() {
	local name="$1"
	command -v "$name" >/dev/null 2>&1 || {
		echo "ERROR: Required command '$name' not found in PATH" >&2
		exit 1
	}
}

ensure_extension() {
	local ext="$1"
	if ! az extension show --name "$ext" >/dev/null 2>&1; then
		echo "Installing Azure CLI extension: $ext"
		az extension add --name "$ext" --output none
	fi
}

# Path for generated, shared env values
GENERATED_ENV="$SCRIPT_DIR/.generated.env"

ensure_generated_env() {
	if [[ -f "$GENERATED_ENV" ]]; then
		return 0
	fi

	cat > "$GENERATED_ENV" <<'EOF'
# ------------------------------------------------------------------------------
# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Generated by infra scripts. Safe to delete; it will be recreated.
# ------------------------------------------------------------------------------
EOF
}

load_generated_env() {
	[[ -f "$GENERATED_ENV" ]] && source "$GENERATED_ENV"
}

# Extract a value from a semicolon-delimited connection string.
# Example: kv_get "HostName=a;SharedAccessKeyName=b;SharedAccessKey=c" "SharedAccessKey"
kv_get() {
	local s="$1"
	local key="$2"
	local part
	IFS=';' read -r -a parts <<< "$s"
	for part in "${parts[@]}"; do
		if [[ "$part" == "$key="* ]]; then
			echo "${part#${key}=}"
			return 0
		fi
	done
	return 1
}

# ------------------------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------------------------

require_cmd az

require_var AZURE_SUBSCRIPTION_ID
require_var AZURE_RESOURCE_GROUP
require_var AZURE_LOCATION

require_var IOTHUB_NAME
require_var IOTHUB_SKU
require_var IOTHUB_UNITS
require_var IOTHUB_RETENTION_DAYS

# ------------------------------------------------------------------------------
# Azure context
# ------------------------------------------------------------------------------

echo "Using subscription: $AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"

# IoT extension
ensure_extension azure-iot

# Ensure generated env exists and load any existing values
ensure_generated_env
load_generated_env

# ------------------------------------------------------------------------------
# IoT Hub
# ------------------------------------------------------------------------------

if az iot hub show --name "$IOTHUB_NAME" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
	echo "IoT Hub '$IOTHUB_NAME' already exists."
else
	echo "WARNING: A new Azure IoT Hub will be created."
	echo "  Name     : $IOTHUB_NAME"
	echo "  SKU      : $IOTHUB_SKU"
	echo "  Units    : $IOTHUB_UNITS"
	echo "  Location : $AZURE_LOCATION"
	echo
	echo "Press Ctrl+C within the next 10 seconds to cancel."
	sleep 10

	echo "Creating IoT Hub '$IOTHUB_NAME'..."
	az iot hub create \
		--name "$IOTHUB_NAME" \
		--resource-group "$AZURE_RESOURCE_GROUP" \
		--location "$AZURE_LOCATION" \
		--sku "$IOTHUB_SKU" \
		--unit "$IOTHUB_UNITS" \
		--output none
	echo "IoT Hub created."
fi

# ------------------------------------------------------------------------------
# Ensure built-in endpoint retention time
# ------------------------------------------------------------------------------

# Validate retention days (integer 1..7)
if ! [[ "$IOTHUB_RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
	echo "ERROR: IOTHUB_RETENTION_DAYS must be an integer (1..7). Got: '$IOTHUB_RETENTION_DAYS'" >&2
	exit 1
fi

if (( IOTHUB_RETENTION_DAYS < 1 || IOTHUB_RETENTION_DAYS > 7 )); then
	echo "ERROR: IOTHUB_RETENTION_DAYS out of range (1..7). Got: '$IOTHUB_RETENTION_DAYS'" >&2
	exit 1
fi

CURRENT_RETENTION="$(az iot hub show \
	--name "$IOTHUB_NAME" \
	--resource-group "$AZURE_RESOURCE_GROUP" \
	--query "properties.eventHubEndpoints.events.retentionTimeInDays" \
	--output tsv)"

if [[ -z "$CURRENT_RETENTION" ]]; then
	echo "ERROR: Failed to read current IoT Hub retentionTimeInDays" >&2
	exit 1
fi

echo "IoT Hub built-in endpoint retention: current=${CURRENT_RETENTION}d, desired=${IOTHUB_RETENTION_DAYS}d"

if [[ "$CURRENT_RETENTION" != "$IOTHUB_RETENTION_DAYS" ]]; then
	echo "Updating IoT Hub retentionTimeInDays to ${IOTHUB_RETENTION_DAYS} days..."
	az iot hub update \
		--name "$IOTHUB_NAME" \
		--resource-group "$AZURE_RESOURCE_GROUP" \
		--set properties.eventHubEndpoints.events.retentionTimeInDays="$IOTHUB_RETENTION_DAYS" \
		--output none
	echo "IoT Hub retention updated."
fi

# ------------------------------------------------------------------------------
# Safety check: ensure no custom routing endpoints are configured
# ------------------------------------------------------------------------------

CUSTOM_ENDPOINTS_JSON="$(az iot hub show \
	--name "$IOTHUB_NAME" \
	--resource-group "$AZURE_RESOURCE_GROUP" \
	--query "properties.routing.endpoints" \
	--output json)"

# Detect any non-empty endpoint arrays (eventHubs, serviceBusQueues, serviceBusTopics, storageContainers)
if echo "$CUSTOM_ENDPOINTS_JSON" | grep -Eq '"eventHubs"\s*:\s*\[[^]]+\]|"serviceBusQueues"\s*:\s*\[[^]]+\]|"serviceBusTopics"\s*:\s*\[[^]]+\]|"storageContainers"\s*:\s*\[[^]]+\]'; then
	echo "ERROR: IoT Hub '$IOTHUB_NAME' has custom routing endpoints configured." >&2
	echo "These are NOT expected when ingest reads directly from the built-in Event Hub-compatible endpoint." >&2
	echo >&2
	echo "Configured routing endpoints:" >&2
	echo "$CUSTOM_ENDPOINTS_JSON" >&2
	echo >&2
	echo "Please remove custom routing endpoints manually and re-run this script." >&2
	exit 1
fi

# ------------------------------------------------------------------------------
# Derive Event Hub-compatible endpoint details and persist to .generated.env
# ------------------------------------------------------------------------------

# Event Hub-compatible endpoint (sb://...)
IOTHUB_EVENTHUB_ENDPOINT="$(az iot hub show \
	--name "$IOTHUB_NAME" \
	--resource-group "$AZURE_RESOURCE_GROUP" \
	--query "properties.eventHubEndpoints.events.endpoint" \
	--output tsv)"

# Portal calls this 'Event Hub-compatible name' and it is the IoT Hub name.
IOTHUB_EVENTHUB_NAME="$IOTHUB_NAME"

# Use iothubowner policy to read shared access keys (Azure built-in policy).
IOTHUB_OWNER_CS="$(az iot hub connection-string show \
	--hub-name "$IOTHUB_NAME" \
	--resource-group "$AZURE_RESOURCE_GROUP" \
	--policy-name iothubowner \
	--query connectionString \
	--output tsv)"

IOTHUB_SAK_NAME="$(kv_get "$IOTHUB_OWNER_CS" "SharedAccessKeyName")"
IOTHUB_SAK="$(kv_get "$IOTHUB_OWNER_CS" "SharedAccessKey")"

# Build an Event Hub-compatible connection string for triggers/consumers.
# Format: Endpoint=sb://...;SharedAccessKeyName=...;SharedAccessKey=...;EntityPath=<eventhub-compatible-name>
IOTHUB_EVENTHUB_CONNECTION_STRING="Endpoint=${IOTHUB_EVENTHUB_ENDPOINT};SharedAccessKeyName=${IOTHUB_SAK_NAME};SharedAccessKey=${IOTHUB_SAK};EntityPath=${IOTHUB_EVENTHUB_NAME}"

cat >> "$GENERATED_ENV" <<EOF

# ------------------------------------------------------------------------------
# IoT Hub (derived)
# ------------------------------------------------------------------------------
IOTHUB_EVENTHUB_ENDPOINT="$IOTHUB_EVENTHUB_ENDPOINT"
IOTHUB_EVENTHUB_NAME="$IOTHUB_EVENTHUB_NAME"
IOTHUB_EVENTHUB_CONNECTION_STRING="$IOTHUB_EVENTHUB_CONNECTION_STRING"
EOF

echo "Wrote IoT Hub derived settings to $GENERATED_ENV"