#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Load base env
source "$SCRIPT_DIR/../azure.env"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

require_var() {
	local name="$1"
	if [[ -z "${!name:-}" ]]; then
		echo "ERROR: Required env var '$name' is not set" >&2
		exit 1
	fi
}

require_cmd() {
	local name="$1"
	command -v "$name" >/dev/null 2>&1 || {
		echo "ERROR: Required command '$name' not found in PATH" >&2
		exit 1
	}
}

# Path for generated, shared env values
GENERATED_ENV="$SCRIPT_DIR/.generated.env"

ensure_generated_env() {
	if [[ -f "$GENERATED_ENV" ]]; then
		return 0
	fi

	cat > "$GENERATED_ENV" <<'EOF'
# ------------------------------------------------------------------------------
# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Generated by infra scripts. Safe to delete; it will be recreated.
# ------------------------------------------------------------------------------
EOF
}

load_generated_env() {
	[[ -f "$GENERATED_ENV" ]] && source "$GENERATED_ENV"
}

# ------------------------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------------------------

require_cmd az

require_var AZURE_SUBSCRIPTION_ID
require_var AZURE_RESOURCE_GROUP
require_var AZURE_LOCATION

require_var FUNCTIONAPP_STORAGE_ACCOUNT
require_var QUEUE_DB_WRITE
require_var QUEUE_ALERTS
require_var QUEUE_BLOB_BATCH

# Cold storage container (used by blob batch writer)
require_var COLD_CONTAINER

# ------------------------------------------------------------------------------
# Azure context
# ------------------------------------------------------------------------------

echo "Using subscription: $AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"

ensure_generated_env
load_generated_env

# ------------------------------------------------------------------------------
# Storage account
# ------------------------------------------------------------------------------

STORAGE_NAME="$FUNCTIONAPP_STORAGE_ACCOUNT"

if az storage account show --name "$STORAGE_NAME" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
	echo "Storage account '$STORAGE_NAME' already exists."
else
	echo "WARNING: A new Azure Storage Account will be created."
	echo "  Name     : $STORAGE_NAME"
	echo "  Location : $AZURE_LOCATION"
	echo
	echo "Press Ctrl+C within the next 10 seconds to cancel."
	sleep 10

	echo "Creating storage account '$STORAGE_NAME'..."
	# NOTE: Storage accounts require globally-unique names.
	az storage account create \
		--name "$STORAGE_NAME" \
		--resource-group "$AZURE_RESOURCE_GROUP" \
		--location "$AZURE_LOCATION" \
		--sku Standard_LRS \
		--kind StorageV2 \
		--https-only true \
		--min-tls-version TLS1_2 \
		--output none
	echo "Storage account created."
fi

# Connection string for queues/blobs and Function runtime
STORAGE_CONNECTION_STRING="$(az storage account show-connection-string \
	--name "$STORAGE_NAME" \
	--resource-group "$AZURE_RESOURCE_GROUP" \
	--query connectionString \
	--output tsv)"

cat >> "$GENERATED_ENV" <<EOF

# ------------------------------------------------------------------------------
# Storage (derived)
# ------------------------------------------------------------------------------
STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING"
FUNCTIONAPP_STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING"

# Cold storage (blob-writer)
COLD_STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING"
EOF

# ------------------------------------------------------------------------------
# Queues
# ------------------------------------------------------------------------------

# Queue operations need either a key/connection string. Use the connection string.
ensure_queue() {
	local q="$1"
	if az storage queue show \
		--name "$q" \
		--connection-string "$STORAGE_CONNECTION_STRING" \
		--query name \
		--output tsv >/dev/null 2>&1; then
		echo "Queue '$q' already exists."
		return 0
	fi

	echo "Creating queue '$q'..."
	az storage queue create \
		--name "$q" \
		--connection-string "$STORAGE_CONNECTION_STRING" \
		--output none
	return 0
}

echo "Ensuring required queues exist..."
ensure_queue "$QUEUE_DB_WRITE"
ensure_queue "$QUEUE_ALERTS"
ensure_queue "$QUEUE_BLOB_BATCH"

# ------------------------------------------------------------------------------
# Optional blob container for cold storage
# ------------------------------------------------------------------------------

if [[ -n "$COLD_CONTAINER" ]]; then
	if az storage container show \
		--name "$COLD_CONTAINER" \
		--connection-string "$STORAGE_CONNECTION_STRING" \
		--query name \
		--output tsv >/dev/null 2>&1; then
		echo "Blob container '$COLD_CONTAINER' already exists."
	else
		echo "Creating blob container '$COLD_CONTAINER'..."
		az storage container create \
			--name "$COLD_CONTAINER" \
			--connection-string "$STORAGE_CONNECTION_STRING" \
			--output none
	fi
fi

echo "Storage + queues setup complete. Wrote settings to $GENERATED_ENV"