#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Load base env
source "$SCRIPT_DIR/../azure.env"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

require_var() {
	local name="$1"
	if [[ -z "${!name:-}" ]]; then
		echo "ERROR: Required env var '$name' is not set" >&2
		exit 1
	fi
}

require_cmd() {
	local name="$1"
	command -v "$name" >/dev/null 2>&1 || {
		echo "ERROR: Required command '$name' not found in PATH" >&2
		exit 1
	}
}

# Path for generated, shared env values
GENERATED_ENV="$SCRIPT_DIR/.generated.env"

ensure_generated_env() {
	if [[ -f "$GENERATED_ENV" ]]; then
		return 0
	fi

	cat > "$GENERATED_ENV" <<'EOF'
# ------------------------------------------------------------------------------
# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Generated by infra scripts. Safe to delete; it will be recreated.
# ------------------------------------------------------------------------------
EOF
}

load_generated_env() {
	[[ -f "$GENERATED_ENV" ]] && source "$GENERATED_ENV"
}

# ------------------------------------------------------------------------------
# Preconditions
# ------------------------------------------------------------------------------

require_cmd az
require_cmd psql

require_var AZURE_SUBSCRIPTION_ID
require_var AZURE_RESOURCE_GROUP

# Flexible Server config
require_var POSTGRES_TIER
require_var POSTGRES_HOST
require_var POSTGRES_PORT
require_var POSTGRES_DATABASE
require_var POSTGRES_USER
require_var POSTGRES_PASSWORD
require_var POSTGRES_SSLMODE
require_var POSTGRES_LOCATION
require_var POSTGRES_VERSION
require_var TIMESCALE_SCHEMA_DIR

# Derive server name from host unless explicitly overridden
POSTGRES_SERVER_NAME="${POSTGRES_SERVER_NAME:-${POSTGRES_HOST%%.*}}"

# ------------------------------------------------------------------------------
# Azure context
# ------------------------------------------------------------------------------

echo "Using subscription: $AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"

ensure_generated_env
load_generated_env

# ------------------------------------------------------------------------------
# Ensure PostgreSQL Flexible Server
# ------------------------------------------------------------------------------

if az postgres flexible-server show --name "$POSTGRES_SERVER_NAME" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
	echo "PostgreSQL server '$POSTGRES_SERVER_NAME' already exists."
else
	echo "WARNING: A new Azure PostgreSQL Flexible Server will be created."
	echo "  Server   : $POSTGRES_SERVER_NAME"
	echo "  Host     : $POSTGRES_HOST"
	echo "  Location : $POSTGRES_LOCATION"
	echo "  Version  : $POSTGRES_VERSION"
	echo "  Tier     : $POSTGRES_TIER"
	echo
	echo "Press Ctrl+C within the next 10 seconds to cancel."
	sleep 10

	echo "Creating PostgreSQL Flexible Server '$POSTGRES_SERVER_NAME'..."
	az postgres flexible-server create \
		--resource-group "$AZURE_RESOURCE_GROUP" \
		--name "$POSTGRES_SERVER_NAME" \
		--location "$POSTGRES_LOCATION" \
		--tier "$POSTGRES_TIER" \
		--version "$POSTGRES_VERSION" \
		--admin-user "$POSTGRES_USER" \
		--admin-password "$POSTGRES_PASSWORD" \
		--public-access 0.0.0.0 \
		--yes \
		--output none
	echo "PostgreSQL server created."
fi

# ------------------------------------------------------------------------------
# Ensure database
# ------------------------------------------------------------------------------

if az postgres flexible-server db show \
	--resource-group "$AZURE_RESOURCE_GROUP" \
	--server-name "$POSTGRES_SERVER_NAME" \
	--database-name "$POSTGRES_DATABASE" >/dev/null 2>&1; then
	echo "Database '$POSTGRES_DATABASE' already exists."
else
	echo "WARNING: A new PostgreSQL database will be created."
	echo "  Server   : $POSTGRES_SERVER_NAME"
	echo "  Database : $POSTGRES_DATABASE"
	echo
	echo "Press Ctrl+C within the next 10 seconds to cancel."
	sleep 10

	echo "Creating database '$POSTGRES_DATABASE'..."
	az postgres flexible-server db create \
		--resource-group "$AZURE_RESOURCE_GROUP" \
		--server-name "$POSTGRES_SERVER_NAME" \
		--database-name "$POSTGRES_DATABASE" \
		--output none
	echo "Database created."
fi

# ------------------------------------------------------------------------------
# Write connection string to .generated.env (always)
# ------------------------------------------------------------------------------

POSTGRES_CONNECTION_STRING="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=${POSTGRES_SSLMODE}"

cat >> "$GENERATED_ENV" <<EOF

# ------------------------------------------------------------------------------
# PostgreSQL (derived)
# ------------------------------------------------------------------------------
POSTGRES_SERVER_NAME="$POSTGRES_SERVER_NAME"
POSTGRES_CONNECTION_STRING="$POSTGRES_CONNECTION_STRING"
EOF

echo "Wrote PostgreSQL derived settings to $GENERATED_ENV"

# ------------------------------------------------------------------------------
# Run schemas (idempotent)
# ------------------------------------------------------------------------------

schema_files=()

BASE_DIR="$SCRIPT_DIR/.."
SCHEMA_ROOT="$TIMESCALE_SCHEMA_DIR"
if [[ "$SCHEMA_ROOT" != /* ]]; then
	SCHEMA_ROOT="$BASE_DIR/$SCHEMA_ROOT"
fi

if [[ ! -d "$SCHEMA_ROOT" ]]; then
	echo "ERROR: TIMESCALE_SCHEMA_DIR does not exist or is not a directory: $SCHEMA_ROOT" >&2
	exit 1
fi

while IFS= read -r -d '' f; do
	schema_files+=("$f")
done < <(find "$SCHEMA_ROOT" -maxdepth 1 -type f -name "*.sql" -print0 | sort -z)

if [[ ${#schema_files[@]} -eq 0 ]]; then
	echo "ERROR: No .sql files found in TIMESCALE_SCHEMA_DIR: $SCHEMA_ROOT" >&2
	exit 1
fi

echo "Running schema files (${#schema_files[@]}) against ${POSTGRES_HOST}/${POSTGRES_DATABASE}..."

export PGPASSWORD="$POSTGRES_PASSWORD"

for f in "${schema_files[@]}"; do
	echo "Applying: $f"
	psql \
		--host "$POSTGRES_HOST" \
		--port "$POSTGRES_PORT" \
		--username "$POSTGRES_USER" \
		--dbname "$POSTGRES_DATABASE" \
		--set ON_ERROR_STOP=1 \
		--file "$f"
done

unset PGPASSWORD

echo "PostgreSQL setup complete."
