#!/usr/bin/env bash
set -euo pipefail

# -----------------------------
# Configurable defaults
# -----------------------------
# Try to auto-detect repo root using git; fall back to script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if git_root=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null); then
	REPO_ROOT_DEFAULT="$git_root"
else
	# scripts/ -> raspberry/ -> repo root
	REPO_ROOT_DEFAULT="$(cd "$SCRIPT_DIR/../.." && pwd)"
fi

CONFIG_DEFAULT="$REPO_ROOT_DEFAULT/raspberry/config/config.json"
SYSTEMD_DIR="/etc/systemd/system"
ENV_FILE="/etc/savonia-iot/env"

# -----------------------------
# Prefer system-wide Node/NPM.
# - Pi 4/5 typically installs to /usr/bin via apt.
# - Pi Zero (ARMv6) is often installed to /usr/local via unofficial builds.
# Resolve the exact binaries so install/build and systemd units can use the same Node.
if [[ -x "/usr/bin/node" ]]; then
	NODE_BIN="/usr/bin/node"
else
	NODE_BIN="$(command -v node || true)"
fi

if [[ -x "/usr/bin/npm" ]]; then
	NPM_BIN="/usr/bin/npm"
else
	NPM_BIN="$(command -v npm || true)"
fi

# Prefer PATH that includes both common locations; we'll prepend the detected Node/NPM directory later too.
BASE_PATH="/usr/bin:/usr/local/bin:$PATH"

# -----------------------------
# Args
# -----------------------------
REPO_ROOT="${1:-$REPO_ROOT_DEFAULT}"
CONFIG_PATH="${2:-$CONFIG_DEFAULT}"

# Use the invoking user for ownership and for systemd units unless a dedicated service user is used.
INSTALL_USER="${SUDO_USER:-$(id -un)}"

if [[ ! -d "$REPO_ROOT" ]]; then
	echo "ERROR: Repo root not found: $REPO_ROOT"
	exit 1
fi

if [[ -z "$NODE_BIN" || ! -x "$NODE_BIN" ]]; then
	echo "ERROR: node not found in PATH. Install Node.js system-wide." >&2
	echo "Pi 4/5: sudo apt install -y nodejs npm" >&2
	echo "Pi Zero (ARMv6): install an ARMv6 build of Node (often to /usr/local/bin)." >&2
	exit 1
fi

if [[ -z "$NPM_BIN" || ! -x "$NPM_BIN" ]]; then
	echo "ERROR: npm not found in PATH. Install npm (often included with Node.js) so the installer can run npm ci/build." >&2
	exit 1
fi


if [[ ! -f "$CONFIG_PATH" ]]; then
	echo "ERROR: Config not found: $CONFIG_PATH"
	exit 1
fi

# -----------------------------
# Ensure device.location exists in config.json
# -----------------------------
# If config is missing device.location, ask for it and write back to config.
DEVICE_LOCATION="$("$NODE_BIN" -e "
const fs=require('fs');
const p=process.argv[1];
const cfg=JSON.parse(fs.readFileSync(p,'utf8'));
process.stdout.write((cfg.device && typeof cfg.device.location==='string' && cfg.device.location.trim()) ? cfg.device.location.trim() : '');
" "$CONFIG_PATH")"

if [[ -z "$DEVICE_LOCATION" ]]; then
	DEFAULT_LOCATION="Living room"
	echo "device.location is not set in $CONFIG_PATH"
	read -r -p "Enter device.location [${DEFAULT_LOCATION}]: " DEVICE_LOCATION
	DEVICE_LOCATION="${DEVICE_LOCATION:-$DEFAULT_LOCATION}"

	# Persist back to config.json
	"$NODE_BIN" -e "
const fs=require('fs');
const p=process.argv[1];
const location=process.argv[2];
const cfg=JSON.parse(fs.readFileSync(p,'utf8'));
cfg.device = cfg.device && typeof cfg.device === 'object' ? cfg.device : {};
cfg.device.location = location;
fs.writeFileSync(p, JSON.stringify(cfg, null, 2) + '\n', 'utf8');
" "$CONFIG_PATH" "$DEVICE_LOCATION"

	echo "Set device.location=\"$DEVICE_LOCATION\" in $CONFIG_PATH"
fi

# -----------------------------
# IoT Hub connection string (.env for systemd services)
# -----------------------------
# IMPORTANT:
# - If the env file already exists, DO NOT modify it on reinstall.
#   Assume it is correct. If the user needs to change the key,
#   they must remove the env file and rerun this installer.
# - If the env file does not exist, create it once (autogenerated).

if [[ -f "$ENV_FILE" ]]; then
	echo "Using existing env file: $ENV_FILE"
	echo "NOTE: To change the IoT Hub key, remove $ENV_FILE and rerun this installer."
else
	# If already set in environment, use it.
	# Otherwise, prompt for it.
	if [[ -z "${IOT_HUB_CONNECTION_STRING:-}" ]]; then
		echo "IOT_HUB_CONNECTION_STRING is not set and $ENV_FILE does not exist."
		echo "An env file will be autogenerated for systemd services."
		read -r -s -p "Enter IOT_HUB_CONNECTION_STRING (input hidden): " IOT_HUB_CONNECTION_STRING
		echo ""
		if [[ -z "$IOT_HUB_CONNECTION_STRING" ]]; then
			echo "ERROR: IOT_HUB_CONNECTION_STRING cannot be empty"
			exit 1
		fi
	fi

	echo "Autogenerating env file: $ENV_FILE"
	sudo mkdir -p "$(dirname "$ENV_FILE")"
	# Quote the value to prevent shell splitting on ';' when sourced
	# Azure connection strings do not contain double quotes, so this is safe
	printf '# Autogenerated by install.sh\n# To change the IoT Hub key, delete this file and rerun the installer.\nIOT_HUB_CONNECTION_STRING="%s"\n' "$IOT_HUB_CONNECTION_STRING" | sudo tee "$ENV_FILE" >/dev/null
	sudo chmod 600 "$ENV_FILE"
	sudo chown "$INSTALL_USER:$INSTALL_USER" "$ENV_FILE"
fi

echo "Repo root : $REPO_ROOT"
echo "Config    : $CONFIG_PATH"

# -----------------------------
# Build (assumes node/npm already installed)
# -----------------------------
echo "Installing dependencies and building..."
cd "$REPO_ROOT"

# Ensure npm uses the same Node (important when multiple Node installs exist).
NODE_DIR="$(dirname "$NODE_BIN")"
PATH="$NODE_DIR:$BASE_PATH"

echo "Using Node: $($NODE_BIN -v) ($NODE_BIN)"
echo "Using npm : $($NPM_BIN -v) ($NPM_BIN)"

"$NPM_BIN" ci

# Build workspace packages by their package.json "name" values
"$NPM_BIN" run -w @savonia-iot/common build
"$NPM_BIN" run -w @savonia-iot/raspberry build

# -----------------------------
# Create runtime directories (best effort)
# -----------------------------
echo "Creating runtime directories..."
sudo mkdir -p /var/lib/savonia-iot /var/log/savonia-iot
sudo chown -R "$INSTALL_USER:$INSTALL_USER" /var/lib/savonia-iot /var/log/savonia-iot

# -----------------------------
# Install base unit files
# -----------------------------
echo "Installing systemd unit templates..."
sudo cp "$REPO_ROOT/raspberry/scripts/systemd/savonia-iot-transferrer.service" "$SYSTEMD_DIR/"
sudo cp "$REPO_ROOT/raspberry/scripts/systemd/savonia-iot-sensor@.service" "$SYSTEMD_DIR/"

# Patch WorkingDirectory and config path inside the two base units
# - WorkingDirectory must match the actual clone location (REPO_ROOT)
# - --config path must match CONFIG_PATH
sudo sed -i "s|^WorkingDirectory=.*$|WorkingDirectory=$REPO_ROOT|" "$SYSTEMD_DIR/savonia-iot-transferrer.service"
sudo sed -i "s|^WorkingDirectory=.*$|WorkingDirectory=$REPO_ROOT|" "$SYSTEMD_DIR/savonia-iot-sensor@.service"

sudo sed -i "s|^User=.*$|User=$INSTALL_USER|" "$SYSTEMD_DIR/savonia-iot-transferrer.service"
sudo sed -i "s|^User=.*$|User=$INSTALL_USER|" "$SYSTEMD_DIR/savonia-iot-sensor@.service"

sudo sed -i "s|--config .*config.json|--config $CONFIG_PATH|g" "$SYSTEMD_DIR/savonia-iot-transferrer.service"
sudo sed -i "s|--config .*config.json|--config $CONFIG_PATH|g" "$SYSTEMD_DIR/savonia-iot-sensor@.service"

# Ensure services load environment variables from the shared env file
for unit in "$SYSTEMD_DIR/savonia-iot-transferrer.service" "$SYSTEMD_DIR/savonia-iot-sensor@.service"; do
	if ! sudo grep -q "^EnvironmentFile=$ENV_FILE$" "$unit"; then
		# Insert right after [Service]
		sudo sed -i "/^\[Service\]/a EnvironmentFile=$ENV_FILE" "$unit"
	fi
done

# Ensure unit files use the detected Node binary (works for /usr/bin/node and /usr/local/bin/node).
for unit in "$SYSTEMD_DIR/savonia-iot-transferrer.service" "$SYSTEMD_DIR/savonia-iot-sensor@.service"; do
	# Replace common hardcoded node paths
	sudo sed -i "s|/usr/bin/node|$NODE_BIN|g" "$unit"
	sudo sed -i "s|/usr/local/bin/node|$NODE_BIN|g" "$unit"
	# If ExecStart uses bare `node`, make it explicit
	sudo sed -i "s|^ExecStart=node |ExecStart=$NODE_BIN |" "$unit"
done

# -----------------------------
# Generate transferrer timer (start on boot)
# -----------------------------
echo "Generating transferrer timer..."
cat <<EOF | sudo tee "$SYSTEMD_DIR/savonia-iot-transferrer.timer" >/dev/null
[Unit]
Description=Savonia IoT - Start Measurement Transferrer on boot

[Timer]
OnBootSec=15s
AccuracySec=1s
Unit=savonia-iot-transferrer.service

[Install]
WantedBy=timers.target
EOF

# -----------------------------
# Generate per-sensor timers from config.json
# -----------------------------
echo "Generating per-sensor timers from config..."

SENSOR_LIST_JSON="$("$NODE_BIN" -e "
const fs=require('fs');
const cfg=JSON.parse(fs.readFileSync('$CONFIG_PATH','utf8'));
if(!cfg.sensors || !Array.isArray(cfg.sensors)) { process.exit(2); }
const out = cfg.sensors.map(s => ({ sensorId: s.sensorId, intervalMs: s.intervalMs }));
process.stdout.write(JSON.stringify(out));
")"

# Validate we got something sensible
if [[ -z "$SENSOR_LIST_JSON" ]]; then
	echo "ERROR: Failed to read sensors from config"
	exit 1
fi

# Remove old generated timers
echo "Removing old generated sensor timer units..."
sudo rm -f "$SYSTEMD_DIR/savonia-iot-sensor-"*.timer

# Create a timer for each sensorId
"$NODE_BIN" -e "
const sensors = JSON.parse(process.argv[1]);
for (const s of sensors) {
	if (!s.sensorId) throw new Error('sensorId missing');
	if (!s.intervalMs || s.intervalMs <= 0) throw new Error('intervalMs missing/invalid for ' + s.sensorId);

	const unitName = 'savonia-iot-sensor-' + s.sensorId + '.timer';
	const serviceInstance = 'savonia-iot-sensor@' + s.sensorId + '.service';

	// systemd supports ms suffix (e.g. 60000ms)
	const timer = [
		'[Unit]',
		'Description=Savonia IoT - Run sensor ' + s.sensorId,
		'',
		'[Timer]',
		'OnBootSec=15s',
		'OnUnitActiveSec=' + s.intervalMs + 'ms',
		'AccuracySec=1s',
		'Unit=' + serviceInstance,
		'',
		'[Install]',
		'WantedBy=timers.target',
		''
	].join('\\n');

	console.log('@@UNIT ' + unitName);
	process.stdout.write(timer + '\\n');
	console.log('@@END');
}
" "$SENSOR_LIST_JSON" | while IFS= read -r line; do
	if [[ "$line" == @@UNIT* ]]; then
		UNIT_NAME="${line#@@UNIT }"
		UNIT_PATH="$SYSTEMD_DIR/$UNIT_NAME"
		CONTENT=""
		continue
	fi

	if [[ "$line" == "@@END" ]]; then
		if [[ -z "${UNIT_NAME:-}" ]]; then
			echo "ERROR: encountered @@END without @@UNIT" >&2
			exit 1
		fi
		echo "Writing $UNIT_PATH"
		echo "$CONTENT" | sudo tee "$UNIT_PATH" >/dev/null
		unset UNIT_NAME
		unset UNIT_PATH
		CONTENT=""
		continue
	fi

	# Accumulate content lines
	if [[ -n "${UNIT_NAME:-}" ]]; then
		CONTENT+="$line"$'\n'
	fi
done

# Cleanup accidental broken unit files from older buggy installer (best effort)
sudo rm -f "$SYSTEMD_DIR/[Unit]" "$SYSTEMD_DIR/[Timer]" "$SYSTEMD_DIR/[Install]" 2>/dev/null || true

# -----------------------------
# Reload systemd and enable services
# -----------------------------
echo "Reloading systemd..."
sudo systemctl daemon-reload

echo "Enabling and starting transferrer timer..."
sudo systemctl enable --now savonia-iot-transferrer.timer

echo "Enabling and starting sensor timers..."
for timer in $(ls "$SYSTEMD_DIR"/savonia-iot-sensor-*.timer 2>/dev/null | xargs -n1 basename); do
	sudo systemctl enable --now "$timer"
done

echo ""
echo "Install complete."
echo "Check status:"
echo "  systemctl status savonia-iot-transferrer.service"
echo "  systemctl status savonia-iot-transferrer.timer"
echo "  systemctl list-timers | grep savonia"
echo "Logs:"
echo "  journalctl -u savonia-iot-transferrer.service -f"